/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kana;

import java.awt.Toolkit;
import java.io.*;
import java.util.*;
import javax.swing.*;
import sun.audio.*;

/**
 *
 * @author kienah
 * Dina Marcaida Fajardo :)
 * a wannabe pro programmer and multilingual computer languages :P
 */
public class kanaGui extends javax.swing.JFrame {

    public kanaGui() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/japan_green.jpg"))); 
        
        cbAllClicked();
        
        panelNotVisible();
        panelSymbols.setVisible(true);
        
        btnQuit.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAbout = new javax.swing.JButton();
        btnSymbols = new javax.swing.JButton();
        btnTutorial = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        footerCurvature = new javax.swing.JLabel();
        panelStatistics = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblCorrect = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDifficult = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTested = new javax.swing.JList();
        lblSymbols1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblWrong = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelAbout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelTest = new javax.swing.JPanel();
        lblSymbols = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        txtAnswer = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        panelSettings = new javax.swing.JPanel();
        rbPracBoth = new javax.swing.JRadioButton();
        rbPracHir = new javax.swing.JRadioButton();
        rbShowStats = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        rbPracKat = new javax.swing.JRadioButton();
        rbFifty = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        rbShowHints = new javax.swing.JRadioButton();
        rbTen = new javax.swing.JRadioButton();
        rbTwenty = new javax.swing.JRadioButton();
        panelSymbols = new javax.swing.JPanel();
        cbAll = new javax.swing.JCheckBox();
        cbA = new javax.swing.JCheckBox();
        cbKa = new javax.swing.JCheckBox();
        cbSa = new javax.swing.JCheckBox();
        cbTa = new javax.swing.JCheckBox();
        cbNa = new javax.swing.JCheckBox();
        cbHa = new javax.swing.JCheckBox();
        cbMa = new javax.swing.JCheckBox();
        cbYa = new javax.swing.JCheckBox();
        cbRa = new javax.swing.JCheckBox();
        cbWa = new javax.swing.JCheckBox();
        cbGa = new javax.swing.JCheckBox();
        cbZa = new javax.swing.JCheckBox();
        cbDa = new javax.swing.JCheckBox();
        cbBa = new javax.swing.JCheckBox();
        cbPa = new javax.swing.JCheckBox();
        cbPya = new javax.swing.JCheckBox();
        cbBya = new javax.swing.JCheckBox();
        cbJa = new javax.swing.JCheckBox();
        cbGya = new javax.swing.JCheckBox();
        cbRya = new javax.swing.JCheckBox();
        cbMya = new javax.swing.JCheckBox();
        cbHya = new javax.swing.JCheckBox();
        cbNya = new javax.swing.JCheckBox();
        cbCha = new javax.swing.JCheckBox();
        cbSha = new javax.swing.JCheckBox();
        cbKya = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        panelTutorial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(560, 490));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/border.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 90, 160, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/templatemo_side_column_box_bottom.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 350, 160, 40);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbout.setBackground(new java.awt.Color(0, 0, 0));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btna5.jpg"))); // NOI18N
        btnAbout.setBorderPainted(false);
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.setName("btnAbout"); // NOI18N
        btnAbout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn5.jpg"))); // NOI18N
        btnAbout.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn5.jpg"))); // NOI18N
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutClicked(evt);
            }
        });
        jPanel2.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 30));

        btnSymbols.setBackground(new java.awt.Color(0, 0, 0));
        btnSymbols.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btna1.jpg"))); // NOI18N
        btnSymbols.setBorderPainted(false);
        btnSymbols.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSymbols.setName("btnSymbols"); // NOI18N
        btnSymbols.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn1.jpg"))); // NOI18N
        btnSymbols.setSelected(true);
        btnSymbols.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn1.jpg"))); // NOI18N
        btnSymbols.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSymbolsClicked(evt);
            }
        });
        jPanel2.add(btnSymbols, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        btnTutorial.setBackground(new java.awt.Color(0, 0, 0));
        btnTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btna2.jpg"))); // NOI18N
        btnTutorial.setBorderPainted(false);
        btnTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTutorial.setName("btnTutorial"); // NOI18N
        btnTutorial.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn2.jpg"))); // NOI18N
        btnTutorial.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn2.jpg"))); // NOI18N
        btnTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTutorialClicked(evt);
            }
        });
        jPanel2.add(btnTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        btnTest.setBackground(new java.awt.Color(0, 0, 0));
        btnTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btna3.jpg"))); // NOI18N
        btnTest.setBorderPainted(false);
        btnTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTest.setName("btnTest"); // NOI18N
        btnTest.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn3.jpg"))); // NOI18N
        btnTest.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn3.jpg"))); // NOI18N
        btnTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTestClicked(evt);
            }
        });
        jPanel2.add(btnTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        btnSettings.setBackground(new java.awt.Color(0, 0, 0));
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btna4.jpg"))); // NOI18N
        btnSettings.setBorderPainted(false);
        btnSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings.setName("btnSettings"); // NOI18N
        btnSettings.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn4.jpg"))); // NOI18N
        btnSettings.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn4.jpg"))); // NOI18N
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingsClicked(evt);
            }
        });
        jPanel2.add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btnQuit1.jpg"))); // NOI18N
        btnQuit.setBorderPainted(false);
        btnQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btnQuit.jpg"))); // NOI18N
        btnQuit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btnQuit.jpg"))); // NOI18N
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        jPanel2.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 79, 30));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 120, 160, 250);

        footerCurvature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/templatemo_main_column_section_bottom.jpg"))); // NOI18N
        getContentPane().add(footerCurvature);
        footerCurvature.setBounds(200, 380, 336, 40);

        panelStatistics.setBackground(new java.awt.Color(0, 0, 0));
        panelStatistics.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelStatistics.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 5, -1, -1));
        panelStatistics.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 260, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 204, 0));
        jLabel12.setText("Wrong:");
        panelStatistics.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));
        panelStatistics.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 260, 10));
        panelStatistics.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 260, 10));

        lblCorrect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(255, 255, 255));
        lblCorrect.setText("Correct:");
        panelStatistics.add(lblCorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 262, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 204, 0));
        jLabel14.setText("STATISTICS");
        panelStatistics.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 204, 0));
        jLabel15.setText("Difficult Symbols:");
        panelStatistics.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jScrollPane3.setBackground(java.awt.Color.black);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jListDifficult.setBackground(new java.awt.Color(0, 0, 0));
        jListDifficult.setForeground(new java.awt.Color(255, 255, 255));
        jListDifficult.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListDifficult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jListDifficult.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jListDifficult.setPreferredSize(new java.awt.Dimension(164, 94));
        jListDifficult.setSelectedIndices(new int[] {-1});
        jScrollPane3.setViewportView(jListDifficult);

        panelStatistics.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 90, 100));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(90, 120));

        jListTested.setBackground(java.awt.Color.black);
        jListTested.setForeground(new java.awt.Color(255, 255, 255));
        jListTested.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListTested.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jListTested.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jListTested.setPreferredSize(new java.awt.Dimension(164, 94));
        jListTested.setSelectedIndices(new int[] {-1});
        jScrollPane4.setViewportView(jListTested);
        jListTested.getAccessibleContext().setAccessibleParent(jScrollPane3);

        panelStatistics.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 100));

        lblSymbols1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/japan_green.jpg"))); // NOI18N
        lblSymbols1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(153, 153, 0)));
        panelStatistics.add(lblSymbols1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 170, 80));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 204, 0));
        jLabel16.setText("Correct:");
        panelStatistics.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 262, -1, -1));

        lblWrong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWrong.setForeground(new java.awt.Color(255, 255, 255));
        lblWrong.setText("Wrong:");
        panelStatistics.add(lblWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 204, 0));
        jLabel17.setText("Tested Symbols:");
        panelStatistics.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        getContentPane().add(panelStatistics);
        panelStatistics.setBounds(200, 90, 336, 310);

        panelAbout.setBackground(new java.awt.Color(0, 0, 0));
        panelAbout.setPreferredSize(new java.awt.Dimension(366, 366));
        panelAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/templatemo_banner.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        panelAbout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 280, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mySignature.png"))); // NOI18N
        panelAbout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        panelAbout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 320, 180));

        getContentPane().add(panelAbout);
        panelAbout.setBounds(200, 90, 336, 310);

        panelTest.setBackground(new java.awt.Color(0, 0, 0));
        panelTest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSymbols.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/japan_green.jpg"))); // NOI18N
        lblSymbols.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(153, 153, 0)));
        panelTest.add(lblSymbols, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/start.jpg"))); // NOI18N
        btnStart.setBorderPainted(false);
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/start1.jpg"))); // NOI18N
        btnStart.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/start1.jpg"))); // NOI18N
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartClicked(evt);
            }
        });
        panelTest.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 260, 49));

        txtAnswer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAnswer.setToolTipText("");
        txtAnswer.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 0), new java.awt.Color(153, 153, 0)));
        panelTest.add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 184, 30));

        lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setText("Starting...");
        panelTest.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btnSubmit1.jpg"))); // NOI18N
        btnSubmit.setBorderPainted(false);
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btnSubmit.jpg"))); // NOI18N
        btnSubmit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btnSubmit.jpg"))); // NOI18N
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        panelTest.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 79, 30));

        lblScore.setBackground(new java.awt.Color(0, 0, 0));
        lblScore.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("Score: ");
        panelTest.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        getContentPane().add(panelTest);
        panelTest.setBounds(200, 90, 336, 310);

        panelSettings.setBackground(new java.awt.Color(0, 0, 0));
        panelSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbPracBoth.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbPracBoth);
        rbPracBoth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPracBoth.setForeground(new java.awt.Color(255, 255, 255));
        rbPracBoth.setText("Practice Both");
        rbPracBoth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPracticeActionPerformed(evt);
            }
        });
        panelSettings.add(rbPracBoth, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        rbPracHir.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbPracHir);
        rbPracHir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPracHir.setForeground(new java.awt.Color(255, 255, 255));
        rbPracHir.setSelected(true);
        rbPracHir.setText("Practice Hiragana");
        rbPracHir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPracticeActionPerformed(evt);
            }
        });
        panelSettings.add(rbPracHir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        rbShowStats.setBackground(new java.awt.Color(0, 0, 0));
        rbShowStats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbShowStats.setForeground(new java.awt.Color(255, 255, 255));
        rbShowStats.setSelected(true);
        rbShowStats.setText("Show Statistics");
        panelSettings.add(rbShowStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        panelSettings.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 260, 20));

        rbPracKat.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbPracKat);
        rbPracKat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPracKat.setForeground(new java.awt.Color(255, 255, 255));
        rbPracKat.setText("Practice Katakana");
        rbPracKat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPracticeActionPerformed(evt);
            }
        });
        panelSettings.add(rbPracKat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        rbFifty.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbFifty);
        rbFifty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbFifty.setForeground(new java.awt.Color(255, 255, 255));
        rbFifty.setText("Range 1 - 50");
        rbFifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRangeActionPerformed(evt);
            }
        });
        panelSettings.add(rbFifty, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        panelSettings.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 260, 20));

        rbShowHints.setBackground(new java.awt.Color(0, 0, 0));
        rbShowHints.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbShowHints.setForeground(new java.awt.Color(255, 255, 255));
        rbShowHints.setText("Show Hints");
        panelSettings.add(rbShowHints, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        rbTen.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbTen);
        rbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbTen.setForeground(new java.awt.Color(255, 255, 255));
        rbTen.setSelected(true);
        rbTen.setText("Range 1 - 10");
        rbTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRangeActionPerformed(evt);
            }
        });
        panelSettings.add(rbTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        rbTwenty.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbTwenty);
        rbTwenty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbTwenty.setForeground(new java.awt.Color(255, 255, 255));
        rbTwenty.setText("Range 1 - 20");
        rbTwenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRangeActionPerformed(evt);
            }
        });
        panelSettings.add(rbTwenty, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        getContentPane().add(panelSettings);
        panelSettings.setBounds(200, 90, 336, 310);

        panelSymbols.setBackground(new java.awt.Color(0, 0, 0));
        panelSymbols.setPreferredSize(new java.awt.Dimension(366, 366));
        panelSymbols.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbAll.setBackground(new java.awt.Color(0, 0, 0));
        cbAll.setForeground(new java.awt.Color(255, 255, 255));
        cbAll.setSelected(true);
        cbAll.setText("All");
        cbAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbAllClickedEvent(evt);
            }
        });
        panelSymbols.add(cbAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cbA.setBackground(new java.awt.Color(0, 0, 0));
        cbA.setForeground(new java.awt.Color(255, 255, 255));
        cbA.setText("a i u e o");
        panelSymbols.add(cbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        cbKa.setBackground(new java.awt.Color(0, 0, 0));
        cbKa.setForeground(new java.awt.Color(255, 255, 255));
        cbKa.setText("ka ki ku ke ko");
        panelSymbols.add(cbKa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cbSa.setBackground(new java.awt.Color(0, 0, 0));
        cbSa.setForeground(new java.awt.Color(255, 255, 255));
        cbSa.setText("sa shi su se so");
        panelSymbols.add(cbSa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cbTa.setBackground(new java.awt.Color(0, 0, 0));
        cbTa.setForeground(new java.awt.Color(255, 255, 255));
        cbTa.setText("ta chi tsu te to");
        panelSymbols.add(cbTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cbNa.setBackground(new java.awt.Color(0, 0, 0));
        cbNa.setForeground(new java.awt.Color(255, 255, 255));
        cbNa.setText("na ni nu ne no");
        panelSymbols.add(cbNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cbHa.setBackground(new java.awt.Color(0, 0, 0));
        cbHa.setForeground(new java.awt.Color(255, 255, 255));
        cbHa.setText("ha hi hu he ho");
        panelSymbols.add(cbHa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cbMa.setBackground(new java.awt.Color(0, 0, 0));
        cbMa.setForeground(new java.awt.Color(255, 255, 255));
        cbMa.setText("ma mi mu me mo");
        panelSymbols.add(cbMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        cbYa.setBackground(new java.awt.Color(0, 0, 0));
        cbYa.setForeground(new java.awt.Color(255, 255, 255));
        cbYa.setText("ya yu yo");
        panelSymbols.add(cbYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        cbRa.setBackground(new java.awt.Color(0, 0, 0));
        cbRa.setForeground(new java.awt.Color(255, 255, 255));
        cbRa.setText("ra ri ru re ro");
        panelSymbols.add(cbRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cbWa.setBackground(new java.awt.Color(0, 0, 0));
        cbWa.setForeground(new java.awt.Color(255, 255, 255));
        cbWa.setText("wa wo n");
        panelSymbols.add(cbWa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        cbGa.setBackground(new java.awt.Color(0, 0, 0));
        cbGa.setForeground(new java.awt.Color(255, 255, 255));
        cbGa.setText("ga gi gu ge go");
        panelSymbols.add(cbGa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        cbZa.setBackground(new java.awt.Color(0, 0, 0));
        cbZa.setForeground(new java.awt.Color(255, 255, 255));
        cbZa.setText("za ji zu ze zo");
        panelSymbols.add(cbZa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        cbDa.setBackground(new java.awt.Color(0, 0, 0));
        cbDa.setForeground(new java.awt.Color(255, 255, 255));
        cbDa.setText("da di du de do");
        panelSymbols.add(cbDa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        cbBa.setBackground(new java.awt.Color(0, 0, 0));
        cbBa.setForeground(new java.awt.Color(255, 255, 255));
        cbBa.setText("ba bi bu be bo");
        panelSymbols.add(cbBa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        cbPa.setBackground(new java.awt.Color(0, 0, 0));
        cbPa.setForeground(new java.awt.Color(255, 255, 255));
        cbPa.setText("pa pi pu pe po");
        panelSymbols.add(cbPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        cbPya.setBackground(new java.awt.Color(0, 0, 0));
        cbPya.setForeground(new java.awt.Color(255, 255, 255));
        cbPya.setText("pya pyu pyo");
        panelSymbols.add(cbPya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        cbBya.setBackground(new java.awt.Color(0, 0, 0));
        cbBya.setForeground(new java.awt.Color(255, 255, 255));
        cbBya.setText("bya byu byo");
        panelSymbols.add(cbBya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, 20));

        cbJa.setBackground(new java.awt.Color(0, 0, 0));
        cbJa.setForeground(new java.awt.Color(255, 255, 255));
        cbJa.setText("ja ju jo");
        panelSymbols.add(cbJa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 20));

        cbGya.setBackground(new java.awt.Color(0, 0, 0));
        cbGya.setForeground(new java.awt.Color(255, 255, 255));
        cbGya.setText("gya gyu gyo");
        panelSymbols.add(cbGya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        cbRya.setBackground(new java.awt.Color(0, 0, 0));
        cbRya.setForeground(new java.awt.Color(255, 255, 255));
        cbRya.setText("rya ryu ryo");
        panelSymbols.add(cbRya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        cbMya.setBackground(new java.awt.Color(0, 0, 0));
        cbMya.setForeground(new java.awt.Color(255, 255, 255));
        cbMya.setText("mya myu myo");
        panelSymbols.add(cbMya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        cbHya.setBackground(new java.awt.Color(0, 0, 0));
        cbHya.setForeground(new java.awt.Color(255, 255, 255));
        cbHya.setText("hya hyu hyo");
        panelSymbols.add(cbHya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        cbNya.setBackground(new java.awt.Color(0, 0, 0));
        cbNya.setForeground(new java.awt.Color(255, 255, 255));
        cbNya.setText("nya nyu nyo");
        panelSymbols.add(cbNya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        cbCha.setBackground(new java.awt.Color(0, 0, 0));
        cbCha.setForeground(new java.awt.Color(255, 255, 255));
        cbCha.setText("cha chu cho");
        panelSymbols.add(cbCha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        cbSha.setBackground(new java.awt.Color(0, 0, 0));
        cbSha.setForeground(new java.awt.Color(255, 255, 255));
        cbSha.setText("sha shu sho");
        panelSymbols.add(cbSha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        cbKya.setBackground(new java.awt.Color(0, 0, 0));
        cbKya.setForeground(new java.awt.Color(255, 255, 255));
        cbKya.setText("kya kyu kyo");
        panelSymbols.add(cbKya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tag.jpg"))); // NOI18N
        panelSymbols.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 40));

        getContentPane().add(panelSymbols);
        panelSymbols.setBounds(200, 90, 336, 310);

        panelTutorial.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(panelTutorial);
        panelTutorial.setBounds(200, 90, 336, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/border2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 80, 340, 21);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/templatemo_footer.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 400, 580, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/templatemo_content_top.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 50, 590, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/templatemo_banner.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 560, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 570, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void setToNotSelected(){
        btnSymbols.setSelected(false);
        btnTutorial.setSelected(false);
        btnTest.setSelected(false);
        btnSettings.setSelected(false);
        btnAbout.setSelected(false);
    }
    
    private void panelNotVisible(){
        panelSymbols.setVisible(false);
        panelTutorial.setVisible(false);
        panelTest.setVisible(false);
        panelSettings.setVisible(false);
        panelAbout.setVisible(false);
        
        panelStatistics.setVisible(false);
    }
    
    private void btnSymbolsClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSymbolsClicked
        sound("click");
        setToNotSelected();
        btnSymbols.setSelected(true);
        
        panelNotVisible();
        panelSymbols.setVisible(true);
    }//GEN-LAST:event_btnSymbolsClicked

    private void btnTutorialClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutorialClicked
        sound("click");
        setToNotSelected();
        btnTutorial.setSelected(true);
        
        panelNotVisible();
        panelTutorial.setVisible(true);
    }//GEN-LAST:event_btnTutorialClicked

    private void btnTestClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestClicked
        sound("click");
        setToNotSelected();
        btnTest.setSelected(true);
        
        panelNotVisible();
        panelTest.setVisible(true);
        
        lbl.setVisible(false);
        lblScore.setVisible(false);
        txtAnswer.setVisible(false);
        btnSubmit.setVisible(false);
        btnQuit.setVisible(false);
    }//GEN-LAST:event_btnTestClicked

    private void btnSettingsClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsClicked
        sound("click");
        setToNotSelected();
        btnSettings.setSelected(true);
        
        panelNotVisible();
        panelSettings.setVisible(true);
    }//GEN-LAST:event_btnSettingsClicked

    private void btnAboutClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutClicked
        sound("click");
        setToNotSelected();
        btnAbout.setSelected(true);
        
        panelNotVisible();
        panelAbout.setVisible(true);
    }//GEN-LAST:event_btnAboutClicked

    private void cbAllClicked(){
        if( cbAll.isSelected() == true){
            cbA.setSelected(true);
            cbKa.setSelected(true);
            cbSa.setSelected(true);
            cbTa.setSelected(true);
            cbNa.setSelected(true);
            cbHa.setSelected(true);
            cbMa.setSelected(true);
            cbYa.setSelected(true);
            cbRa.setSelected(true);
            cbWa.setSelected(true);
            cbGa.setSelected(true);
            cbZa.setSelected(true);
            cbDa.setSelected(true);
            cbBa.setSelected(true);
            cbPa.setSelected(true);
            cbPya.setSelected(true);
            cbBya.setSelected(true);
            cbJa.setSelected(true);
            cbGya.setSelected(true);
            cbRya.setSelected(true);
            cbMya.setSelected(true);
            cbHya.setSelected(true);
            cbNya.setSelected(true);
            cbCha.setSelected(true);
            cbSha.setSelected(true);
            cbKya.setSelected(true);
        }else{
            cbA.setSelected(false);
            cbKa.setSelected(false);
            cbSa.setSelected(false);
            cbTa.setSelected(false);
            cbNa.setSelected(false);
            cbHa.setSelected(false);
            cbMa.setSelected(false);
            cbYa.setSelected(false);
            cbRa.setSelected(false);
            cbWa.setSelected(false);
            cbGa.setSelected(false);
            cbZa.setSelected(false);
            cbDa.setSelected(false);
            cbBa.setSelected(false);
            cbPa.setSelected(false);
            cbPya.setSelected(false);
            cbBya.setSelected(false);
            cbJa.setSelected(false);
            cbGya.setSelected(false);
            cbRya.setSelected(false);
            cbMya.setSelected(false);
            cbHya.setSelected(false);
            cbNya.setSelected(false);
            cbCha.setSelected(false);
            cbSha.setSelected(false);
            cbKya.setSelected(false);
        }
    }
    
    private void cbAllClickedEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbAllClickedEvent
        cbAllClicked();
    }//GEN-LAST:event_cbAllClickedEvent

    private int[] selectedSymbols = new int[26];
    private int numOfSelectedSym;
    private void getSelectedSymbols(){
        int ctr = 0;
        numOfSelectedSym = 0;
        
        if(cbA.isSelected() == true){
            selectedSymbols[ctr] = 0;
            ctr++;
            numOfSelectedSym++;
        }if(cbKa.isSelected() == true){
            selectedSymbols[ctr] = 1;
            ctr++;
            numOfSelectedSym++;
        }if(cbSa.isSelected() == true){
            selectedSymbols[ctr] = 2;
            ctr++;
            numOfSelectedSym++;
        }if(cbTa.isSelected() == true){
            selectedSymbols[ctr] = 3;
            ctr++;
            numOfSelectedSym++;
        }if(cbNa.isSelected() == true){
            selectedSymbols[ctr] = 4;
            ctr++;
            numOfSelectedSym++;
        }if(cbHa.isSelected() == true){
            selectedSymbols[ctr] = 5;
            ctr++;
            numOfSelectedSym++;
        }if(cbMa.isSelected() == true){
            selectedSymbols[ctr] = 6;
            ctr++;
            numOfSelectedSym++;
        }if(cbYa.isSelected() == true){
            selectedSymbols[ctr] = 7;
            ctr++;
            numOfSelectedSym++;
        }if(cbRa.isSelected() == true){
            selectedSymbols[ctr] = 8;
            ctr++;
            numOfSelectedSym++;
        }if(cbWa.isSelected() == true){
            selectedSymbols[ctr] = 9;
            ctr++;
            numOfSelectedSym++;
        }if(cbGa.isSelected() == true){
            selectedSymbols[ctr] = 10;
            ctr++;
            numOfSelectedSym++;
        }if(cbZa.isSelected() == true){
            selectedSymbols[ctr] = 11;
            ctr++;
            numOfSelectedSym++;
        }if(cbDa.isSelected() == true){
            selectedSymbols[ctr] = 12;
            ctr++;
            numOfSelectedSym++;
        }if(cbBa.isSelected() == true){
            selectedSymbols[ctr] = 13;
            ctr++;
            numOfSelectedSym++;
        }if(cbPa.isSelected() == true){
            selectedSymbols[ctr] = 14;
            ctr++;
            numOfSelectedSym++;
        }if(cbPya.isSelected() == true){
            selectedSymbols[ctr] = 15;
            ctr++;
            numOfSelectedSym++;
        }if(cbBya.isSelected() == true){
            selectedSymbols[ctr] = 16;
            ctr++;
            numOfSelectedSym++;
        }if(cbJa.isSelected() == true){
            selectedSymbols[ctr] = 17;
            ctr++;
            numOfSelectedSym++;
        }if(cbGya.isSelected() == true){
            selectedSymbols[ctr] = 18;
            ctr++;
            numOfSelectedSym++;
        }if(cbRya.isSelected() == true){
            selectedSymbols[ctr] = 19;
            ctr++;
            numOfSelectedSym++;
        }if(cbMya.isSelected() == true){
            selectedSymbols[ctr] = 20;
            ctr++;
            numOfSelectedSym++;
        }if(cbHya.isSelected() == true){
            selectedSymbols[ctr] = 21;
            ctr++;
            numOfSelectedSym++;
        }if(cbNya.isSelected() == true){
            selectedSymbols[ctr] = 22;
            ctr++;
            numOfSelectedSym++;
        }if(cbCha.isSelected() == true){
            selectedSymbols[ctr] = 23;
            ctr++;
            numOfSelectedSym++;
        }if(cbSha.isSelected() == true){
            selectedSymbols[ctr] = 24;
            ctr++;
            numOfSelectedSym++;
        }if(cbKya.isSelected() == true){
            selectedSymbols[ctr] = 25;
            ctr++;
            numOfSelectedSym++;
        }
            
    }    
    
    
    private String currentSymbol;
    private String selectedPractice = "Hiragana";
    private int selectedRange = 10;
    private int counter;
    private int score;
    private int wrongAns;
    private String[][] symbolsArray = {{"a", "e", "i", "o", "u"},
                                   {"ka", "ke", "ki", "ko", "ku"},
                                   {"sa", "se", "shi", "so", "su"},
                                   {"ta", "te", "chi", "to", "tsu"},
                                   {"na", "ne", "ni", "no", "nu"},
                                   {"ha", "he", "hi", "ho", "hu"},
                                   {"ma", "me", "mi", "mo", "mu"},
                                   {"ya", "yo", "yu", "yo", "yu"},
                                   {"ra", "re", "ri", "ro", "ru"},
                                   {"wa", "wa", "wo", "wo", "n"},
                                   {"ga", "ge", "gi", "go", "gu"},
                                   {"za", "ze", "ji", "zo", "zu"},
                                   {"da", "de", "di", "do", "du"},
                                   {"ba", "be", "bi", "bo", "bu"},
                                   {"pa", "pe", "pi", "po", "pu"},
                                   {"kya", "kyo", "kyu", "kyo", "kyu"},
                                   {"sha", "sho", "shu", "sho", "shu"},
                                   {"cha", "cho", "chu", "cho", "chu"},
                                   {"nya", "nyo", "nyu", "nyo", "nyu"},
                                   {"hya", "hyo", "hyu", "hyo", "hyu"},
                                   {"mya", "myo", "myu", "myo", "myu"},
                                   {"rya", "ryo", "ryu", "ryo", "ryu"},
                                   {"gya", "gyo", "gyu", "gyo", "gyu"},
                                   {"ja", "jo", "ju", "jo", "ju"},
                                   {"ja2", "jo2", "ju2", "jo2", "ju2"},
                                   {"bya", "byo", "byu", "byo", "byu"},
                                   {"pya", "pyo", "pyu", "pyo", "pyu"},
                                  };  
    private void nextSymbol(){
        String routeSymbol = null;
        
        Random generator = new Random();
        int randNumber;
        int randIndex;  // where the first random index of the 2D array is placed
        
        // gets the randomized first index of the 2D array 
        randNumber = Math.abs(generator.nextInt()) % numOfSelectedSym;
        randIndex = selectedSymbols[randNumber];
        
        randNumber = Math.abs(generator.nextInt()) % 5;
        
        currentSymbol = symbolsArray[randIndex][randNumber];
        
        if(rbPracHir.isSelected() == true)
            routeSymbol = "/img/symbols/Hiragana/" + symbolsArray[randIndex][randNumber] + ".jpg";
        else if(rbPracKat.isSelected() == true)
            routeSymbol = "/img/symbols/Katakana/" + symbolsArray[randIndex][randNumber] + ".jpg";
           
        lblSymbols.setIcon(new javax.swing.ImageIcon(getClass().getResource(routeSymbol)));
        //System.out.println("Opps! Theres an error here!");
    }
    
    
    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        sound("click");
        
        lblSymbols.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/japan_green.jpg")));
        btnStart.setVisible(true);
        txtAnswer.setVisible(false);
        btnSubmit.setVisible(false);
        btnQuit.setVisible(false);
        lbl.setVisible(false);
        lblScore.setVisible(false);
        panelStatistics.setVisible(false);
        
        btnSymbols.setVisible(true);
        btnTutorial.setVisible(true);
        btnTest.setVisible(true);
        btnSettings.setVisible(true);
        btnAbout.setVisible(true);
       
    }//GEN-LAST:event_btnQuitMouseClicked

    private void checkAnswer(){
        // if range is reached, then end of test
        if (counter == selectedRange){
            if(txtAnswer.getText().equals(currentSymbol))
                score++;
            else
                wrongAns++;
            
            lbl.setText("Test Completed!");
            lblScore.setText("Score: " + score + " / " + selectedRange);
            
            panelNotVisible();
            panelStatistics.setVisible(true);
            /////////////////////////////////////////////////////////
            // statistics data
            ////////////////////////////////////////////////////////
            DefaultListModel<String> model = new DefaultListModel<>();
            //JList<String> list;
            jListTested = new JList<>(model);
            HashMap<String, String> data = new HashMap<>();
    
            lblCorrect.setText("" + score);
            lblWrong.setText("" + wrongAns);
           
            for(int i=0; i<26; i++){
                for(int j=0; j<5; j++){
                    data.put(symbolsArray[selectedSymbols[i]][j], "/img/symbols/Hiragana/" + symbolsArray[selectedSymbols[i]][j] + ".jpg");
                }
            }
            
            for(Object x: data.keySet()){
                model.addElement(String.valueOf(x));
            }
            
            jScrollPane3 = new JScrollPane(jListTested);
            //  end -- statistics data

        }else{
            if(txtAnswer.getText().equals(currentSymbol)){
                score++;  
            }else{
                wrongAns++;
            }
            
            counter++;  // iterates counter until limit

            lbl.setText(counter + " / " + selectedRange);
            lblScore.setText("Score: " + score);
            nextSymbol();
            
            txtAnswer.setText("");
        }
    }
    
    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        sound("click");
        checkAnswer();
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnStartClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartClicked
        sound("click");
        
        lbl.setVisible(true);

        getSelectedSymbols();
        if(numOfSelectedSym == 0)
        lbl.setText("Opps! No symbol selected!");
        else{
            lblScore.setVisible(true);
            btnStart.setVisible(false);
            txtAnswer.setVisible(true);
            btnSubmit.setVisible(true);
            btnQuit.setVisible(true);

            // hide other buttons during test
            btnSymbols.setVisible(false);
            btnTutorial.setVisible(false);
            btnTest.setVisible(false);
            btnSettings.setVisible(false);
            btnAbout.setVisible(false);

            // set all to default
            counter = 1;
            score = 0;
            wrongAns = 0;
            
            lbl.setText(counter + " / " + selectedRange);
            lblScore.setText("Score: " + score);
            nextSymbol();
        }
    }//GEN-LAST:event_btnStartClicked

    private void rbRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRangeActionPerformed
        if(rbTen.isSelected() == true)
            selectedRange = 10;
        if(rbTwenty.isSelected() == true)
            selectedRange = 20;
        if(rbFifty.isSelected() == true)
            selectedRange = 50;
    }//GEN-LAST:event_rbRangeActionPerformed

    private void rbPracticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPracticeActionPerformed
        if(rbPracBoth.isSelected() == true)
            selectedPractice = "Both";
        if(rbPracHir.isSelected() == true)
            selectedPractice = "Hiragana";
        if(rbPracKat.isSelected() == true)
            selectedPractice = "Katakana";
    }//GEN-LAST:event_rbPracticeActionPerformed
    public static void sound(String soundName){
	InputStream in;
        
        try{
            //in = new FileInputStream("ButtonHover.wav");
            in = new FileInputStream(new File("C:\\Users\\kienah\\Documents\\NetBeansProjects\\kana\\src\\sound\\" + soundName + ".wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kanaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new kanaGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSymbols;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnTutorial;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbA;
    private javax.swing.JCheckBox cbAll;
    private javax.swing.JCheckBox cbBa;
    private javax.swing.JCheckBox cbBya;
    private javax.swing.JCheckBox cbCha;
    private javax.swing.JCheckBox cbDa;
    private javax.swing.JCheckBox cbGa;
    private javax.swing.JCheckBox cbGya;
    private javax.swing.JCheckBox cbHa;
    private javax.swing.JCheckBox cbHya;
    private javax.swing.JCheckBox cbJa;
    private javax.swing.JCheckBox cbKa;
    private javax.swing.JCheckBox cbKya;
    private javax.swing.JCheckBox cbMa;
    private javax.swing.JCheckBox cbMya;
    private javax.swing.JCheckBox cbNa;
    private javax.swing.JCheckBox cbNya;
    private javax.swing.JCheckBox cbPa;
    private javax.swing.JCheckBox cbPya;
    private javax.swing.JCheckBox cbRa;
    private javax.swing.JCheckBox cbRya;
    private javax.swing.JCheckBox cbSa;
    private javax.swing.JCheckBox cbSha;
    private javax.swing.JCheckBox cbTa;
    private javax.swing.JCheckBox cbWa;
    private javax.swing.JCheckBox cbYa;
    private javax.swing.JCheckBox cbZa;
    private javax.swing.JLabel footerCurvature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListDifficult;
    private javax.swing.JList jListTested;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblSymbols;
    private javax.swing.JLabel lblSymbols1;
    private javax.swing.JLabel lblWrong;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JPanel panelStatistics;
    private javax.swing.JPanel panelSymbols;
    private javax.swing.JPanel panelTest;
    private javax.swing.JPanel panelTutorial;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton rbFifty;
    private javax.swing.JRadioButton rbPracBoth;
    private javax.swing.JRadioButton rbPracHir;
    private javax.swing.JRadioButton rbPracKat;
    private javax.swing.JRadioButton rbShowHints;
    private javax.swing.JRadioButton rbShowStats;
    private javax.swing.JRadioButton rbTen;
    private javax.swing.JRadioButton rbTwenty;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
